name: htk.js
markdown: redcarpet
highlighter: rouge
exclude: [vendor]

copyright:
  author: Hacktoolkit
  url: http://www.hacktoolkit.com
  year: 2015

htk:
  credits: true
  mobile: true
  show_footer: true
  javascripts:
  templates:

meta:
  description: Jekyll Hacktoolkit. HTML5 Boilerplate inspired. Opinionated framework.
  keywords: hacktoolkit,htk,jekyll,html5,css3

libs:
  css:
    jqueryui: 1.11.4
    pure: 0.6.0
  js:
    backbone: 1.2.3
    jquery: 2.2.1
    jqueryui: 1.11.4
    lodash: 4.5.1
    parse: 1.3.5
    yui: 3.18.1

api:
  facebook:
    app_id:
  google:
    maps:
      init: false
      key:
      sensor: true
      default_lat: -34.397
      default_lng: 150.644
      default_zoom: 8
      container: map_canvas
  parse:
    app_id:
    js_key:
  rollbar:
    access_token:

fonts:
  google: Cabin+Condensed:400,500,600,700
